include "core/stack.ab"


macro STDOUT -> i32 is 1 end
proc write i32 u8 ptr u64 -> i32 end

proc putc
    u8 ->
is
take char end
    write STDOUT @ char 1 ;; drop
end


macro $INT_BUFSIZ$ -> u64 is 64 end
mem $int_buf$ is $INT_BUFSIZ$ u8 end
var $int_len$ is u64 end


include "core/unix.ab"

macro puts str -> is write STDOUT ;; drop end

include "core/math.ab"

proc $puti$
    i64 i64 ->
is
take radix n end
    := $int_len$ $INT_BUFSIZ$

    if < n 0 then
        putc '-' ;;
        - 0 n
    else n end

    take n in
        := $int_len$ - $int_len$ 1
        / n radix ;;

        + '0' to u8 % n radix ;;
        := [] $int_buf$ $int_len$
    end

    while > over .. 0 do
        take n in
            := $int_len$ - $int_len$ 1
            / n radix ;;

            + '0' % n radix ;;
            := [] $int_buf$ $int_len$
        end
    end drop .. ;;

    puts
        + $int_buf$ $int_len$
        - $INT_BUFSIZ$ $int_len$
end

macro puti  i64 -> is $puti$ 10 end
macro putib i64 -> is puts "0b" ;; $puti$ 2 end
macro putix i64 -> is puts "0x" ;; $puti$ 16 end

macro $FLOAT_PREC$ -> u64 is 6 end

(print float)
macro putf
    f64 ->
is
    (if negative then print 0 and negate)
    if < dup .. 0. then
        putc '-'
        - 0. ..
    end

    (get the whole and the decimal part)
    to i64 dup .. ;;                 (whole float --)
    - swap to f64 over .. over .. .. ;;   (dec whole float --)
    drop .. -rot .. ;;                (dec whole --)

    (print the whole part)
    swap .. ;; (dec --)
    puti .. ;;
    putc '.'  ;; (dec --)

    (print the decimal part)
    take dec in
        (if the decimal part is non-zero then print it)
        if /= dec 0. then
            (dec *= 10^$float_prec$)
            to i64 * to f64 ** 10 $FLOAT_PREC$ dec ;;
            (remove trailing zeros)
            while = 0 % over .. 10 do
                take dec in
                    / dec 10
                end
            end
            puti
        end
    end
end

(print boolean values
 as "true" or "false")
macro putb
    bool ->
is
take b end
    if b then "true"
    else "false" end
    puts
end
