include "linux.ab"

(socket domain)
macro AF_UNSPEC     is 0          end
macro AF_LOCAL      is 1          end
macro AF_UNIX       is PF_LOCAL   end
macro AF_FILE       is PF_LOCAL   end
macro AF_INET       is 2          end
macro AF_AX25       is 3          end
macro AF_IPX        is 4          end
macro AF_APPLETALK  is 5	      end
macro AF_NETROM     is 6          end
macro AF_BRIDGE     is 7          end
macro AF_ATMPVC  	is 8          end
macro AF_X25        is 9          end
macro AF_INET6      is 10         end
macro AF_ROSE       is 11	      end
macro AF_DECnet     is 12         end
macro AF_NETBEUI	is 13         end
macro AF_SECURITY	is 14         end
macro AF_KEY		is 15         end
macro AF_NETLINK	is 16         end
macro AF_ROUTE      is PF_NETLINK end
macro AF_PACKET     is 17         end
macro AF_ASH        is 18         end
macro AF_ECONET     is 19         end
macro AF_ATMSVC     is 20         end
macro AF_RDS		is 21	      end
macro AF_SNA		is 22	      end
macro AF_IRDA		is 23	      end
macro AF_PPPOX	    is 24	      end
macro AF_WANPIPE	is 25	      end
macro AF_LLC		is 26	      end
macro AF_IB		    is 27	      end
macro AF_MPLS		is 28	      end
macro AF_CAN		is 29	      end
macro AF_TIPC		is 30	      end
macro AF_BLUETOOTH	is 31	      end
macro AF_IUCV		is 32	      end
macro AF_RXRPC	    is 33	      end
macro AF_ISDN		is 34	      end
macro AF_PHONET	    is 35	      end
macro AF_IEEE802154	is 36	      end
macro AF_CAIF		is 37	      end
macro AF_ALG		is 38	      end
macro AF_NFC		is 39	      end
macro AF_VSOCK	    is 40	      end
macro AF_KCM		is 41	      end
macro AF_QIPCRTR	is 42	      end
macro AF_SMC		is 43	      end
macro AF_XDP		is 44	      end
macro AF_MCTP		is 45	      end
macro AF_MAX		is 46	      end

(socket type)
macro SOCK_STREAM    is 1        end
macro SOCK_DGRAM     is 2        end
macro SOCK_RAW       is 3        end
macro SOCK_RDM       is 4        end
macro SOCK_SEQPACKET is 5        end
macro SOCK_DCCP      is 6        end
macro SOCK_PACKET    is 10       end
macro SOCK_CLOEXEC   is 02000000 end
macro SOCK_NONBLOCK  is 00004000 end

macro sa_family_t is int end

struct sockaddr is
    .sa_family  sa_family_t
    .sa_data    int
end end

macro socket
    int int int
    -> int
is
    syscall 3 SYS_socket
end

macro bind
    int ptr:sockaddr socklen_t
    -> int
is
    syscall 3 SYS_bind
end

macro listen
    int int -> int
is
    syscall 2 SYS_listen
end

macro accept
    int ptr:sockaddr socklen_t
    -> int
is
    syscall 3 SYS_accept
end
